// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: ppm.proto

// import "nanopb.proto";

package gocybertx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line         int32 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Channel      int32 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	ChannelValue int32 `protobuf:"varint,3,opt,name=channel_value,json=channelValue,proto3" json:"channel_value,omitempty"`
}

func (x *UpdateLine) Reset() {
	*x = UpdateLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ppm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLine) ProtoMessage() {}

func (x *UpdateLine) ProtoReflect() protoreflect.Message {
	mi := &file_ppm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLine.ProtoReflect.Descriptor instead.
func (*UpdateLine) Descriptor() ([]byte, []int) {
	return file_ppm_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateLine) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *UpdateLine) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *UpdateLine) GetChannelValue() int32 {
	if x != nil {
		return x.ChannelValue
	}
	return 0
}

type UpdateAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line          int32   `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	ChannelValues []int32 `protobuf:"varint,2,rep,packed,name=channel_values,json=channelValues,proto3" json:"channel_values,omitempty"`
}

func (x *UpdateAll) Reset() {
	*x = UpdateAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ppm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAll) ProtoMessage() {}

func (x *UpdateAll) ProtoReflect() protoreflect.Message {
	mi := &file_ppm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAll.ProtoReflect.Descriptor instead.
func (*UpdateAll) Descriptor() ([]byte, []int) {
	return file_ppm_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAll) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *UpdateAll) GetChannelValues() []int32 {
	if x != nil {
		return x.ChannelValues
	}
	return nil
}

var File_ppm_proto protoreflect.FileDescriptor

var file_ppm_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x70, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x79, 0x62,
	0x65, 0x72, 0x74, 0x78, 0x22, 0x5f, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4a, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x29, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x42, 0x02,
	0x10, 0x01, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x30, 0x2f, 0x63, 0x79, 0x62, 0x65, 0x72, 0x74, 0x78, 0x2f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x63, 0x79, 0x62, 0x65, 0x72, 0x74,
	0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ppm_proto_rawDescOnce sync.Once
	file_ppm_proto_rawDescData = file_ppm_proto_rawDesc
)

func file_ppm_proto_rawDescGZIP() []byte {
	file_ppm_proto_rawDescOnce.Do(func() {
		file_ppm_proto_rawDescData = protoimpl.X.CompressGZIP(file_ppm_proto_rawDescData)
	})
	return file_ppm_proto_rawDescData
}

var file_ppm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ppm_proto_goTypes = []any{
	(*UpdateLine)(nil), // 0: cybertx.UpdateLine
	(*UpdateAll)(nil),  // 1: cybertx.UpdateAll
}
var file_ppm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ppm_proto_init() }
func file_ppm_proto_init() {
	if File_ppm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ppm_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ppm_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ppm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ppm_proto_goTypes,
		DependencyIndexes: file_ppm_proto_depIdxs,
		MessageInfos:      file_ppm_proto_msgTypes,
	}.Build()
	File_ppm_proto = out.File
	file_ppm_proto_rawDesc = nil
	file_ppm_proto_goTypes = nil
	file_ppm_proto_depIdxs = nil
}
