# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='cybertx.messages',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x10\x63ybertx.messages\"O\n\tPPMUpdate\x12\x11\n\x04line\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x05\x12\x15\n\rchannel_value\x18\x03 \x01(\x05\x42\x07\n\x05_line\"B\n\x0cPPMUpdateAll\x12\x11\n\x04line\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\x0e\x63hannel_values\x18\x02 \x03(\x05\x42\x07\n\x05_lineb\x06proto3'
)




_PPMUPDATE = _descriptor.Descriptor(
  name='PPMUpdate',
  full_name='cybertx.messages.PPMUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='cybertx.messages.PPMUpdate.line', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel', full_name='cybertx.messages.PPMUpdate.channel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel_value', full_name='cybertx.messages.PPMUpdate.channel_value', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_line', full_name='cybertx.messages.PPMUpdate._line',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=35,
  serialized_end=114,
)


_PPMUPDATEALL = _descriptor.Descriptor(
  name='PPMUpdateAll',
  full_name='cybertx.messages.PPMUpdateAll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='line', full_name='cybertx.messages.PPMUpdateAll.line', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel_values', full_name='cybertx.messages.PPMUpdateAll.channel_values', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_line', full_name='cybertx.messages.PPMUpdateAll._line',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=116,
  serialized_end=182,
)

_PPMUPDATE.oneofs_by_name['_line'].fields.append(
  _PPMUPDATE.fields_by_name['line'])
_PPMUPDATE.fields_by_name['line'].containing_oneof = _PPMUPDATE.oneofs_by_name['_line']
_PPMUPDATEALL.oneofs_by_name['_line'].fields.append(
  _PPMUPDATEALL.fields_by_name['line'])
_PPMUPDATEALL.fields_by_name['line'].containing_oneof = _PPMUPDATEALL.oneofs_by_name['_line']
DESCRIPTOR.message_types_by_name['PPMUpdate'] = _PPMUPDATE
DESCRIPTOR.message_types_by_name['PPMUpdateAll'] = _PPMUPDATEALL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PPMUpdate = _reflection.GeneratedProtocolMessageType('PPMUpdate', (_message.Message,), {
  'DESCRIPTOR' : _PPMUPDATE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:cybertx.messages.PPMUpdate)
  })
_sym_db.RegisterMessage(PPMUpdate)

PPMUpdateAll = _reflection.GeneratedProtocolMessageType('PPMUpdateAll', (_message.Message,), {
  'DESCRIPTOR' : _PPMUPDATEALL,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:cybertx.messages.PPMUpdateAll)
  })
_sym_db.RegisterMessage(PPMUpdateAll)


# @@protoc_insertion_point(module_scope)
