# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x10\x63ybertx.messages\"O\n\tPPMUpdate\x12\x11\n\x04line\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x05\x12\x15\n\rchannel_value\x18\x03 \x01(\x05\x42\x07\n\x05_line\"B\n\x0cPPMUpdateAll\x12\x11\n\x04line\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x16\n\x0e\x63hannel_values\x18\x02 \x03(\x05\x42\x07\n\x05_lineb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PPMUPDATE']._serialized_start=35
  _globals['_PPMUPDATE']._serialized_end=114
  _globals['_PPMUPDATEALL']._serialized_start=116
  _globals['_PPMUPDATEALL']._serialized_end=182
# @@protoc_insertion_point(module_scope)
