/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cybertx_messages_PPMUpdate, cybertx_messages_PPMUpdate, AUTO)


PB_BIND(cybertx_messages_PPMUpdateAll, cybertx_messages_PPMUpdateAll, AUTO)



