/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "ppm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cybertx_UpdateLine, cybertx_UpdateLine, AUTO)


PB_BIND(cybertx_UpdateAll, cybertx_UpdateAll, AUTO)



