/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_CYBERTX_PPM_PB_H_INCLUDED
#define PB_CYBERTX_PPM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cybertx_UpdateLine {
    int32_t line;
    int32_t channel;
    int32_t channel_value;
} cybertx_UpdateLine;

typedef struct _cybertx_UpdateAll {
    int32_t line;
    pb_size_t channel_values_count;
    int32_t channel_values[16];
} cybertx_UpdateAll;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cybertx_UpdateLine_init_default          {0, 0, 0}
#define cybertx_UpdateAll_init_default           {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define cybertx_UpdateLine_init_zero             {0, 0, 0}
#define cybertx_UpdateAll_init_zero              {0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define cybertx_UpdateLine_line_tag              1
#define cybertx_UpdateLine_channel_tag           2
#define cybertx_UpdateLine_channel_value_tag     3
#define cybertx_UpdateAll_line_tag               1
#define cybertx_UpdateAll_channel_values_tag     2

/* Struct field encoding specification for nanopb */
#define cybertx_UpdateLine_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    line,              1) \
X(a, STATIC,   SINGULAR, INT32,    channel,           2) \
X(a, STATIC,   SINGULAR, INT32,    channel_value,     3)
#define cybertx_UpdateLine_CALLBACK NULL
#define cybertx_UpdateLine_DEFAULT NULL

#define cybertx_UpdateAll_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    line,              1) \
X(a, STATIC,   REPEATED, INT32,    channel_values,    2)
#define cybertx_UpdateAll_CALLBACK NULL
#define cybertx_UpdateAll_DEFAULT NULL

extern const pb_msgdesc_t cybertx_UpdateLine_msg;
extern const pb_msgdesc_t cybertx_UpdateAll_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cybertx_UpdateLine_fields &cybertx_UpdateLine_msg
#define cybertx_UpdateAll_fields &cybertx_UpdateAll_msg

/* Maximum encoded size of messages (where known) */
#define CYBERTX_PPM_PB_H_MAX_SIZE                cybertx_UpdateAll_size
#define cybertx_UpdateAll_size                   187
#define cybertx_UpdateLine_size                  33

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
