# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x10\x63ybertx.messages\"A\n\tPPMUpdate\x12\x0c\n\x04line\x18\x01 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\x05\x12\x15\n\rchannel_value\x18\x03 \x01(\x05\"4\n\x0cPPMUpdateAll\x12\x0c\n\x04line\x18\x01 \x01(\x05\x12\x16\n\x0e\x63hannel_values\x18\x02 \x03(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PPMUPDATE._serialized_start=35
  _PPMUPDATE._serialized_end=100
  _PPMUPDATEALL._serialized_start=102
  _PPMUPDATEALL._serialized_end=154
# @@protoc_insertion_point(module_scope)
