// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ppm.proto

package com.cybertx.protos;

public final class CyberTxProtos {
  private CyberTxProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UpdateLineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cybertx.UpdateLine)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 line = 1;</code>
     * @return The line.
     */
    int getLine();

    /**
     * <code>int32 channel = 2;</code>
     * @return The channel.
     */
    int getChannel();

    /**
     * <code>int32 channel_value = 3;</code>
     * @return The channelValue.
     */
    int getChannelValue();
  }
  /**
   * Protobuf type {@code cybertx.UpdateLine}
   */
  public static final class UpdateLine extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cybertx.UpdateLine)
      UpdateLineOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateLine.newBuilder() to construct.
    private UpdateLine(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateLine() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateLine();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateLine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              line_ = input.readInt32();
              break;
            }
            case 16: {

              channel_ = input.readInt32();
              break;
            }
            case 24: {

              channelValue_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateLine_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateLine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cybertx.protos.CyberTxProtos.UpdateLine.class, com.cybertx.protos.CyberTxProtos.UpdateLine.Builder.class);
    }

    public static final int LINE_FIELD_NUMBER = 1;
    private int line_;
    /**
     * <code>int32 line = 1;</code>
     * @return The line.
     */
    @java.lang.Override
    public int getLine() {
      return line_;
    }

    public static final int CHANNEL_FIELD_NUMBER = 2;
    private int channel_;
    /**
     * <code>int32 channel = 2;</code>
     * @return The channel.
     */
    @java.lang.Override
    public int getChannel() {
      return channel_;
    }

    public static final int CHANNEL_VALUE_FIELD_NUMBER = 3;
    private int channelValue_;
    /**
     * <code>int32 channel_value = 3;</code>
     * @return The channelValue.
     */
    @java.lang.Override
    public int getChannelValue() {
      return channelValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (line_ != 0) {
        output.writeInt32(1, line_);
      }
      if (channel_ != 0) {
        output.writeInt32(2, channel_);
      }
      if (channelValue_ != 0) {
        output.writeInt32(3, channelValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (line_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, line_);
      }
      if (channel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, channel_);
      }
      if (channelValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, channelValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cybertx.protos.CyberTxProtos.UpdateLine)) {
        return super.equals(obj);
      }
      com.cybertx.protos.CyberTxProtos.UpdateLine other = (com.cybertx.protos.CyberTxProtos.UpdateLine) obj;

      if (getLine()
          != other.getLine()) return false;
      if (getChannel()
          != other.getChannel()) return false;
      if (getChannelValue()
          != other.getChannelValue()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel();
      hash = (37 * hash) + CHANNEL_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getChannelValue();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateLine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cybertx.protos.CyberTxProtos.UpdateLine prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cybertx.UpdateLine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cybertx.UpdateLine)
        com.cybertx.protos.CyberTxProtos.UpdateLineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateLine_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateLine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cybertx.protos.CyberTxProtos.UpdateLine.class, com.cybertx.protos.CyberTxProtos.UpdateLine.Builder.class);
      }

      // Construct using com.cybertx.protos.CyberTxProtos.UpdateLine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        line_ = 0;

        channel_ = 0;

        channelValue_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateLine_descriptor;
      }

      @java.lang.Override
      public com.cybertx.protos.CyberTxProtos.UpdateLine getDefaultInstanceForType() {
        return com.cybertx.protos.CyberTxProtos.UpdateLine.getDefaultInstance();
      }

      @java.lang.Override
      public com.cybertx.protos.CyberTxProtos.UpdateLine build() {
        com.cybertx.protos.CyberTxProtos.UpdateLine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cybertx.protos.CyberTxProtos.UpdateLine buildPartial() {
        com.cybertx.protos.CyberTxProtos.UpdateLine result = new com.cybertx.protos.CyberTxProtos.UpdateLine(this);
        result.line_ = line_;
        result.channel_ = channel_;
        result.channelValue_ = channelValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cybertx.protos.CyberTxProtos.UpdateLine) {
          return mergeFrom((com.cybertx.protos.CyberTxProtos.UpdateLine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cybertx.protos.CyberTxProtos.UpdateLine other) {
        if (other == com.cybertx.protos.CyberTxProtos.UpdateLine.getDefaultInstance()) return this;
        if (other.getLine() != 0) {
          setLine(other.getLine());
        }
        if (other.getChannel() != 0) {
          setChannel(other.getChannel());
        }
        if (other.getChannelValue() != 0) {
          setChannelValue(other.getChannelValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cybertx.protos.CyberTxProtos.UpdateLine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cybertx.protos.CyberTxProtos.UpdateLine) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int line_ ;
      /**
       * <code>int32 line = 1;</code>
       * @return The line.
       */
      @java.lang.Override
      public int getLine() {
        return line_;
      }
      /**
       * <code>int32 line = 1;</code>
       * @param value The line to set.
       * @return This builder for chaining.
       */
      public Builder setLine(int value) {
        
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 line = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLine() {
        
        line_ = 0;
        onChanged();
        return this;
      }

      private int channel_ ;
      /**
       * <code>int32 channel = 2;</code>
       * @return The channel.
       */
      @java.lang.Override
      public int getChannel() {
        return channel_;
      }
      /**
       * <code>int32 channel = 2;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(int value) {
        
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 channel = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        
        channel_ = 0;
        onChanged();
        return this;
      }

      private int channelValue_ ;
      /**
       * <code>int32 channel_value = 3;</code>
       * @return The channelValue.
       */
      @java.lang.Override
      public int getChannelValue() {
        return channelValue_;
      }
      /**
       * <code>int32 channel_value = 3;</code>
       * @param value The channelValue to set.
       * @return This builder for chaining.
       */
      public Builder setChannelValue(int value) {
        
        channelValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 channel_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelValue() {
        
        channelValue_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cybertx.UpdateLine)
    }

    // @@protoc_insertion_point(class_scope:cybertx.UpdateLine)
    private static final com.cybertx.protos.CyberTxProtos.UpdateLine DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cybertx.protos.CyberTxProtos.UpdateLine();
    }

    public static com.cybertx.protos.CyberTxProtos.UpdateLine getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateLine>
        PARSER = new com.google.protobuf.AbstractParser<UpdateLine>() {
      @java.lang.Override
      public UpdateLine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateLine(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateLine> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateLine> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cybertx.protos.CyberTxProtos.UpdateLine getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpdateAllOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cybertx.UpdateAll)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 line = 1;</code>
     * @return The line.
     */
    int getLine();

    /**
     * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
     * @return A list containing the channelValues.
     */
    java.util.List<java.lang.Integer> getChannelValuesList();
    /**
     * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
     * @return The count of channelValues.
     */
    int getChannelValuesCount();
    /**
     * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
     * @param index The index of the element to return.
     * @return The channelValues at the given index.
     */
    int getChannelValues(int index);
  }
  /**
   * Protobuf type {@code cybertx.UpdateAll}
   */
  public static final class UpdateAll extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cybertx.UpdateAll)
      UpdateAllOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UpdateAll.newBuilder() to construct.
    private UpdateAll(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UpdateAll() {
      channelValues_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UpdateAll();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UpdateAll(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              line_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                channelValues_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              channelValues_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                channelValues_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                channelValues_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          channelValues_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateAll_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateAll_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cybertx.protos.CyberTxProtos.UpdateAll.class, com.cybertx.protos.CyberTxProtos.UpdateAll.Builder.class);
    }

    public static final int LINE_FIELD_NUMBER = 1;
    private int line_;
    /**
     * <code>int32 line = 1;</code>
     * @return The line.
     */
    @java.lang.Override
    public int getLine() {
      return line_;
    }

    public static final int CHANNEL_VALUES_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList channelValues_;
    /**
     * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
     * @return A list containing the channelValues.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getChannelValuesList() {
      return channelValues_;
    }
    /**
     * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
     * @return The count of channelValues.
     */
    public int getChannelValuesCount() {
      return channelValues_.size();
    }
    /**
     * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
     * @param index The index of the element to return.
     * @return The channelValues at the given index.
     */
    public int getChannelValues(int index) {
      return channelValues_.getInt(index);
    }
    private int channelValuesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (line_ != 0) {
        output.writeInt32(1, line_);
      }
      if (getChannelValuesList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(channelValuesMemoizedSerializedSize);
      }
      for (int i = 0; i < channelValues_.size(); i++) {
        output.writeInt32NoTag(channelValues_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (line_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, line_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < channelValues_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(channelValues_.getInt(i));
        }
        size += dataSize;
        if (!getChannelValuesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        channelValuesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cybertx.protos.CyberTxProtos.UpdateAll)) {
        return super.equals(obj);
      }
      com.cybertx.protos.CyberTxProtos.UpdateAll other = (com.cybertx.protos.CyberTxProtos.UpdateAll) obj;

      if (getLine()
          != other.getLine()) return false;
      if (!getChannelValuesList()
          .equals(other.getChannelValuesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine();
      if (getChannelValuesCount() > 0) {
        hash = (37 * hash) + CHANNEL_VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getChannelValuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cybertx.protos.CyberTxProtos.UpdateAll parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cybertx.protos.CyberTxProtos.UpdateAll prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cybertx.UpdateAll}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cybertx.UpdateAll)
        com.cybertx.protos.CyberTxProtos.UpdateAllOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateAll_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateAll_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cybertx.protos.CyberTxProtos.UpdateAll.class, com.cybertx.protos.CyberTxProtos.UpdateAll.Builder.class);
      }

      // Construct using com.cybertx.protos.CyberTxProtos.UpdateAll.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        line_ = 0;

        channelValues_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cybertx.protos.CyberTxProtos.internal_static_cybertx_UpdateAll_descriptor;
      }

      @java.lang.Override
      public com.cybertx.protos.CyberTxProtos.UpdateAll getDefaultInstanceForType() {
        return com.cybertx.protos.CyberTxProtos.UpdateAll.getDefaultInstance();
      }

      @java.lang.Override
      public com.cybertx.protos.CyberTxProtos.UpdateAll build() {
        com.cybertx.protos.CyberTxProtos.UpdateAll result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cybertx.protos.CyberTxProtos.UpdateAll buildPartial() {
        com.cybertx.protos.CyberTxProtos.UpdateAll result = new com.cybertx.protos.CyberTxProtos.UpdateAll(this);
        int from_bitField0_ = bitField0_;
        result.line_ = line_;
        if (((bitField0_ & 0x00000001) != 0)) {
          channelValues_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.channelValues_ = channelValues_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cybertx.protos.CyberTxProtos.UpdateAll) {
          return mergeFrom((com.cybertx.protos.CyberTxProtos.UpdateAll)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cybertx.protos.CyberTxProtos.UpdateAll other) {
        if (other == com.cybertx.protos.CyberTxProtos.UpdateAll.getDefaultInstance()) return this;
        if (other.getLine() != 0) {
          setLine(other.getLine());
        }
        if (!other.channelValues_.isEmpty()) {
          if (channelValues_.isEmpty()) {
            channelValues_ = other.channelValues_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChannelValuesIsMutable();
            channelValues_.addAll(other.channelValues_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cybertx.protos.CyberTxProtos.UpdateAll parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cybertx.protos.CyberTxProtos.UpdateAll) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int line_ ;
      /**
       * <code>int32 line = 1;</code>
       * @return The line.
       */
      @java.lang.Override
      public int getLine() {
        return line_;
      }
      /**
       * <code>int32 line = 1;</code>
       * @param value The line to set.
       * @return This builder for chaining.
       */
      public Builder setLine(int value) {
        
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 line = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLine() {
        
        line_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList channelValues_ = emptyIntList();
      private void ensureChannelValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          channelValues_ = mutableCopy(channelValues_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
       * @return A list containing the channelValues.
       */
      public java.util.List<java.lang.Integer>
          getChannelValuesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(channelValues_) : channelValues_;
      }
      /**
       * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
       * @return The count of channelValues.
       */
      public int getChannelValuesCount() {
        return channelValues_.size();
      }
      /**
       * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
       * @param index The index of the element to return.
       * @return The channelValues at the given index.
       */
      public int getChannelValues(int index) {
        return channelValues_.getInt(index);
      }
      /**
       * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
       * @param index The index to set the value at.
       * @param value The channelValues to set.
       * @return This builder for chaining.
       */
      public Builder setChannelValues(
          int index, int value) {
        ensureChannelValuesIsMutable();
        channelValues_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
       * @param value The channelValues to add.
       * @return This builder for chaining.
       */
      public Builder addChannelValues(int value) {
        ensureChannelValuesIsMutable();
        channelValues_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
       * @param values The channelValues to add.
       * @return This builder for chaining.
       */
      public Builder addAllChannelValues(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureChannelValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, channelValues_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 channel_values = 2 [(.nanopb) = { ... }</code>
       * @return This builder for chaining.
       */
      public Builder clearChannelValues() {
        channelValues_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cybertx.UpdateAll)
    }

    // @@protoc_insertion_point(class_scope:cybertx.UpdateAll)
    private static final com.cybertx.protos.CyberTxProtos.UpdateAll DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cybertx.protos.CyberTxProtos.UpdateAll();
    }

    public static com.cybertx.protos.CyberTxProtos.UpdateAll getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateAll>
        PARSER = new com.google.protobuf.AbstractParser<UpdateAll>() {
      @java.lang.Override
      public UpdateAll parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateAll(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UpdateAll> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpdateAll> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cybertx.protos.CyberTxProtos.UpdateAll getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cybertx_UpdateLine_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cybertx_UpdateLine_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cybertx_UpdateAll_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cybertx_UpdateAll_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tppm.proto\022\007cybertx\032\014nanopb.proto\"B\n\nUp" +
      "dateLine\022\014\n\004line\030\001 \001(\005\022\017\n\007channel\030\002 \001(\005\022" +
      "\025\n\rchannel_value\030\003 \001(\005\"=\n\tUpdateAll\022\014\n\004l" +
      "ine\030\001 \001(\005\022\"\n\016channel_values\030\002 \003(\005B\n\222?\002\020\020" +
      "\222?\002x\001B#\n\022com.cybertx.protosB\rCyberTxProt" +
      "osb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Nanopb.getDescriptor(),
        });
    internal_static_cybertx_UpdateLine_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cybertx_UpdateLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cybertx_UpdateLine_descriptor,
        new java.lang.String[] { "Line", "Channel", "ChannelValue", });
    internal_static_cybertx_UpdateAll_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cybertx_UpdateAll_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cybertx_UpdateAll_descriptor,
        new java.lang.String[] { "Line", "ChannelValues", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(Nanopb.nanopb);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    Nanopb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
